class BuiltInLogTemplateDefinition {
  const BuiltInLogTemplateDefinition({
    required this.id,
    required this.templateKey,
    required this.name,
    required this.fields,
  });

  final String id;
  final String templateKey;
  final String name;
  final List<Map<String, dynamic>> fields;
}

const List<BuiltInLogTemplateDefinition> builtInLogTemplateDefinitions = [
  BuiltInLogTemplateDefinition(
    id: 'builtin:bills',
    templateKey: 'bills',
    name: 'Bills',
    fields: [
      {
        'field_key': 'name',
        'label': 'Bill name',
        'field_type': 'text',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'category',
        'label': 'Category',
        'field_type': 'dropdown',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'currency',
        'label': 'Currency',
        'field_type': 'dropdown',
        'sort_order': 3,
        'is_hidden': false,
      },
      {
        'field_key': 'amount',
        'label': 'Amount',
        'field_type': 'number',
        'sort_order': 4,
        'is_hidden': false,
      },
      {
        'field_key': 'is_paid',
        'label': 'Paid?',
        'field_type': 'bool',
        'sort_order': 5,
        'is_hidden': false,
      },
      {
        'field_key': 'notes',
        'label': 'Notes',
        'field_type': 'text',
        'sort_order': 6,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:books',
    templateKey: 'books',
    name: 'Books',
    fields: [
      {
        'field_key': 'book_title',
        'label': 'Book title',
        'field_type': 'text',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'author',
        'label': 'Author',
        'field_type': 'text',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'category',
        'label': 'Category',
        'field_type': 'dropdown',
        'sort_order': 3,
        'is_hidden': false,
      },
      {
        'field_key': 'current_page',
        'label': 'Current page',
        'field_type': 'number',
        'sort_order': 4,
        'is_hidden': false,
      },
      {
        'field_key': 'rating',
        'label': 'Rating',
        'field_type': 'rating',
        'sort_order': 5,
        'is_hidden': false,
      },
      {
        'field_key': 'notes',
        'label': 'Notes',
        'field_type': 'text',
        'sort_order': 6,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:cycle',
    templateKey: 'cycle',
    name: 'Menstrual cycle',
    fields: [
      {
        'field_key': 'flow',
        'label': 'Flow',
        'field_type': 'dropdown',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'symptoms',
        'label': 'Symptoms',
        'field_type': 'multi_select',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'cramps',
        'label': 'Cramps',
        'field_type': 'rating',
        'sort_order': 3,
        'is_hidden': false,
      },
      {
        'field_key': 'libido',
        'label': 'Libido',
        'field_type': 'rating',
        'sort_order': 4,
        'is_hidden': false,
      },
      {
        'field_key': 'energy_level',
        'label': 'Energy',
        'field_type': 'rating',
        'sort_order': 5,
        'is_hidden': false,
      },
      {
        'field_key': 'stress_level',
        'label': 'Stress',
        'field_type': 'rating',
        'sort_order': 6,
        'is_hidden': false,
      },
      {
        'field_key': 'pregnancy_test',
        'label': 'Pregnancy test',
        'field_type': 'dropdown',
        'sort_order': 7,
        'is_hidden': false,
      },
      {
        'field_key': 'notes',
        'label': 'Notes',
        'field_type': 'text',
        'sort_order': 8,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:expenses',
    templateKey: 'expenses',
    name: 'Expenses',
    fields: [
      {
        'field_key': 'item_service',
        'label': 'Item/Service',
        'field_type': 'text',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'category',
        'label': 'Category',
        'field_type': 'dropdown',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'currency',
        'label': 'Currency',
        'field_type': 'dropdown',
        'sort_order': 3,
        'is_hidden': false,
      },
      {
        'field_key': 'cost',
        'label': 'Cost',
        'field_type': 'number',
        'sort_order': 4,
        'is_hidden': false,
      },
      {
        'field_key': 'status',
        'label': 'Status',
        'field_type': 'dropdown',
        'sort_order': 5,
        'is_hidden': false,
      },
      {
        'field_key': 'notes',
        'label': 'Notes',
        'field_type': 'text',
        'sort_order': 6,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:fast',
    templateKey: 'fast',
    name: 'Fast',
    fields: [
      {
        'field_key': 'duration_hours',
        'label': 'Hours fasted',
        'field_type': 'number',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'feeling',
        'label': 'Feeling',
        'field_type': 'dropdown',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'notes',
        'label': 'Notes',
        'field_type': 'text',
        'sort_order': 3,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:income',
    templateKey: 'income',
    name: 'Income',
    fields: [
      {
        'field_key': 'source',
        'label': 'Source',
        'field_type': 'text',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'status',
        'label': 'Status',
        'field_type': 'dropdown',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'amount',
        'label': 'Amount',
        'field_type': 'number',
        'sort_order': 3,
        'is_hidden': false,
      },
      {
        'field_key': 'category',
        'label': 'Category',
        'field_type': 'dropdown',
        'sort_order': 4,
        'is_hidden': false,
      },
      {
        'field_key': 'currency',
        'label': 'Currency',
        'field_type': 'dropdown',
        'sort_order': 5,
        'is_hidden': false,
      },
      {
        'field_key': 'notes',
        'label': 'Notes',
        'field_type': 'text',
        'sort_order': 6,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:meditation',
    templateKey: 'meditation',
    name: 'Meditation',
    fields: [
      {
        'field_key': 'duration_minutes',
        'label': 'Duration',
        'field_type': 'number',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'technique',
        'label': 'Technique',
        'field_type': 'dropdown',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'focus_rating',
        'label': 'Focus rating',
        'field_type': 'rating',
        'sort_order': 3,
        'is_hidden': false,
      },
      {
        'field_key': 'notes',
        'label': 'Notes',
        'field_type': 'text',
        'sort_order': 4,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:study',
    templateKey: 'study',
    name: 'Study',
    fields: [
      {
        'field_key': 'subject',
        'label': 'Subject',
        'field_type': 'dropdown',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'duration_hours',
        'label': 'Duration (hours)',
        'field_type': 'number',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'study_methods',
        'label': 'Study methods',
        'field_type': 'multi_select',
        'sort_order': 3,
        'is_hidden': false,
      },
      {
        'field_key': 'focus_rating',
        'label': 'Focus rating',
        'field_type': 'rating',
        'sort_order': 4,
        'is_hidden': false,
      },
      {
        'field_key': 'notes',
        'label': 'Notes',
        'field_type': 'text',
        'sort_order': 5,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:movies',
    templateKey: 'movies',
    name: 'Movies',
    fields: [
      {
        'field_key': 'movie_title',
        'label': 'Movie title',
        'field_type': 'text',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'genre',
        'label': 'Genre',
        'field_type': 'dropdown',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'rating',
        'label': 'Rating',
        'field_type': 'rating',
        'sort_order': 3,
        'is_hidden': false,
      },
      {
        'field_key': 'location',
        'label': 'Location',
        'field_type': 'dropdown',
        'sort_order': 4,
        'is_hidden': false,
      },
      {
        'field_key': 'status',
        'label': 'Status',
        'field_type': 'dropdown',
        'sort_order': 5,
        'is_hidden': false,
      },
      {
        'field_key': 'notes',
        'label': 'Notes',
        'field_type': 'text',
        'sort_order': 6,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:medication',
    templateKey: 'medication',
    name: 'Medication',
    fields: [
      {
        'field_key': 'medication_name',
        'label': 'Medication name',
        'field_type': 'text',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'time',
        'label': 'Time',
        'field_type': 'time',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'dosage',
        'label': 'Dosage',
        'field_type': 'text',
        'sort_order': 3,
        'is_hidden': false,
      },
      {
        'field_key': 'status',
        'label': 'Status',
        'field_type': 'dropdown',
        'options': 'Taken,Missed,Skipped',
        'sort_order': 4,
        'is_hidden': false,
      },
      {
        'field_key': 'notes',
        'label': 'Notes',
        'field_type': 'text',
        'sort_order': 5,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:meals',
    templateKey: 'meals',
    name: 'Meals',
    fields: [
      {
        'field_key': 'meal_name',
        'label': 'Meal name',
        'field_type': 'text',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'time',
        'label': 'Time',
        'field_type': 'time',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'meal_type',
        'label': 'Meal type',
        'field_type': 'dropdown',
        'options': 'Breakfast,Lunch,Dinner,Snack',
        'sort_order': 3,
        'is_hidden': false,
      },
      {
        'field_key': 'calories',
        'label': 'Calories',
        'field_type': 'number',
        'sort_order': 4,
        'is_hidden': false,
      },
      {
        'field_key': 'notes',
        'label': 'Notes',
        'field_type': 'text',
        'sort_order': 5,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:places',
    templateKey: 'places',
    name: 'Places',
    fields: [
      {
        'field_key': 'place_name',
        'label': 'Place name',
        'field_type': 'text',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'location',
        'label': 'Location',
        'field_type': 'text',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'rating',
        'label': 'Rating',
        'field_type': 'rating',
        'sort_order': 3,
        'is_hidden': false,
      },
      {
        'field_key': 'notes',
        'label': 'Notes',
        'field_type': 'text',
        'sort_order': 4,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:restaurants',
    templateKey: 'restaurants',
    name: 'Restaurants',
    fields: [
      {
        'field_key': 'restaurant_name',
        'label': 'Restaurant',
        'field_type': 'text',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'cuisine_type',
        'label': 'Cuisine type',
        'field_type': 'dropdown',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'location',
        'label': 'Location',
        'field_type': 'text',
        'sort_order': 3,
        'is_hidden': false,
      },
      {
        'field_key': 'rating',
        'label': 'Rating',
        'field_type': 'rating',
        'sort_order': 4,
        'is_hidden': false,
      },
      {
        'field_key': 'notes',
        'label': 'Notes',
        'field_type': 'text',
        'sort_order': 5,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:skin_care',
    templateKey: 'skin_care',
    name: 'Skin Care',
    fields: [
      {
        'field_key': 'routine_type',
        'label': 'Routine type',
        'field_type': 'dropdown',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'products',
        'label': 'Products',
        'field_type': 'text',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'skin_condition',
        'label': 'Skin condition',
        'field_type': 'dropdown',
        'sort_order': 3,
        'is_hidden': false,
      },
      {
        'field_key': 'notes',
        'label': 'Notes',
        'field_type': 'text',
        'sort_order': 4,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:social',
    templateKey: 'social',
    name: 'Social',
    fields: [
      {
        'field_key': 'person_event',
        'label': 'Person/Event',
        'field_type': 'text',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'activity_type',
        'label': 'Activity type',
        'field_type': 'dropdown',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'people',
        'label': 'People',
        'field_type': 'text',
        'sort_order': 3,
        'is_hidden': false,
      },
      {
        'field_key': 'social_energy',
        'label': 'Social energy',
        'field_type': 'number',
        'sort_order': 4,
        'is_hidden': false,
      },
      {
        'field_key': 'location',
        'label': 'Location',
        'field_type': 'text',
        'sort_order': 5,
        'is_hidden': false,
      },
      {
        'field_key': 'notes',
        'label': 'Notes',
        'field_type': 'text',
        'sort_order': 6,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:mood',
    templateKey: 'mood',
    name: 'Mood',
    fields: [
      {
        'field_key': 'feeling',
        'label': 'Feeling',
        'field_type': 'dropdown',
        'options':
            '😊 Happy,🤩 Excited,😎 Confident,🧘 Calm,😐 Neutral,😔 Sad,😤 Angry,🤯 Stressed,🤔 Anxious,😴 Tired,🤒 Sick,Other',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'intensity',
        'label': 'Intensity',
        'field_type': 'number',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'notes',
        'label': 'Notes',
        'field_type': 'text',
        'sort_order': 3,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:tasks',
    templateKey: 'tasks',
    name: 'Tasks',
    fields: [
      {
        'field_key': 'task_name',
        'label': 'Task name',
        'field_type': 'text',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'priority',
        'label': 'Priority',
        'field_type': 'rating',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'is_done',
        'label': 'Done?',
        'field_type': 'bool',
        'sort_order': 3,
        'is_hidden': false,
      },
      {
        'field_key': 'notes',
        'label': 'Notes',
        'field_type': 'text',
        'sort_order': 4,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:sleep',
    templateKey: 'sleep',
    name: 'Sleep',
    fields: [
      {
        'field_key': 'hours_slept',
        'label': 'Hours slept',
        'field_type': 'number',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'quality',
        'label': 'Quality',
        'field_type': 'rating',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'bedtime',
        'label': 'Bedtime',
        'field_type': 'time',
        'sort_order': 3,
        'is_hidden': false,
      },
      {
        'field_key': 'wake_up_time',
        'label': 'Wake up time',
        'field_type': 'time',
        'sort_order': 4,
        'is_hidden': false,
      },
      {
        'field_key': 'notes',
        'label': 'Notes',
        'field_type': 'text',
        'sort_order': 5,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:tv_log',
    templateKey: 'tv_log',
    name: 'TV Logs',
    fields: [
      {
        'field_key': 'title',
        'label': 'Show title',
        'field_type': 'text',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'genre',
        'label': 'Genre',
        'field_type': 'dropdown',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'rating',
        'label': 'Rating',
        'field_type': 'rating',
        'sort_order': 3,
        'is_hidden': false,
      },
      {
        'field_key': 'status',
        'label': 'Status',
        'field_type': 'dropdown',
        'sort_order': 4,
        'is_hidden': false,
      },
      {
        'field_key': 'thoughts',
        'label': 'Thoughts',
        'field_type': 'text',
        'sort_order': 5,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:wishlist',
    templateKey: 'wishlist',
    name: 'Wishlist',
    fields: [
      {
        'field_key': 'item_name',
        'label': 'Item name',
        'field_type': 'text',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'currency',
        'label': 'Currency',
        'field_type': 'dropdown',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'estimated_price',
        'label': 'Estimated price',
        'field_type': 'number',
        'sort_order': 3,
        'is_hidden': false,
      },
      {
        'field_key': 'priority',
        'label': 'Priority',
        'field_type': 'rating',
        'sort_order': 4,
        'is_hidden': false,
      },
      {
        'field_key': 'status',
        'label': 'Status',
        'field_type': 'dropdown',
        'sort_order': 5,
        'is_hidden': false,
      },
      {
        'field_key': 'notes',
        'label': 'Notes',
        'field_type': 'text',
        'sort_order': 6,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:workout',
    templateKey: 'workout',
    name: 'Workout',
    fields: [
      {
        'field_key': 'exercise',
        'label': 'Exercise',
        'field_type': 'dropdown',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'sets',
        'label': 'Sets',
        'field_type': 'number',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'reps',
        'label': 'Reps',
        'field_type': 'number',
        'sort_order': 3,
        'is_hidden': false,
      },
      {
        'field_key': 'weight_kg',
        'label': 'Weight (kg)',
        'field_type': 'number',
        'sort_order': 4,
        'is_hidden': false,
      },
      {
        'field_key': 'notes',
        'label': 'Notes',
        'field_type': 'text',
        'sort_order': 5,
        'is_hidden': false,
      },
    ],
  ),
  BuiltInLogTemplateDefinition(
    id: 'builtin:water',
    templateKey: 'water',
    name: 'Water',
    fields: [
      {
        'field_key': 'amount',
        'label': 'Amount',
        'field_type': 'number',
        'sort_order': 1,
        'is_hidden': false,
      },
      {
        'field_key': 'unit',
        'label': 'Unit',
        'field_type': 'dropdown',
        'sort_order': 2,
        'is_hidden': false,
      },
      {
        'field_key': 'goal_reached',
        'label': 'Goal reached?',
        'field_type': 'bool',
        'sort_order': 3,
        'is_hidden': false,
      },
    ],
  ),
];

BuiltInLogTemplateDefinition? builtInLogTemplateByKey(String templateKey) {
  final normalized = templateKey.trim().toLowerCase();
  for (final definition in builtInLogTemplateDefinitions) {
    if (definition.templateKey == normalized) {
      return definition;
    }
  }
  return null;
}
